# Generated by Django 5.2.4 on 2025-07-24 23:54

import django.core.validators
import django.db.models.deletion
import gll_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuenoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesosCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='PlacaCheck',
            fields=[
                ('nroPlaca', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallo',
            fields=[
                ('idGallo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaNac', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('tipoGallo', models.CharField(choices=[('DP', 'Gallo De Pelea'), ('PADRE', 'Gallo Padre'), ('MADRE', 'Gallina madre')], max_length=20)),
                ('fechaMuerte', models.DateField(null=True)),
                ('nombre_img', gll_app.models.ImageKitField(max_length=500)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.color')),
                ('estadoDeSalud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.estado')),
                ('nombreDuenoAnterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gll_app.duenoanterior')),
                ('placaMadre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='gll_app.gallo')),
                ('placaPadre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='gll_app.gallo')),
                ('peso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gll_app.pesoscheck')),
                ('nroPlaca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallo_por_placa', to='gll_app.placacheck')),
                ('nroPlacaAnterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallo_por_placa_anterior', to='gll_app.placacheck')),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('idEncuentro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaYHora', models.DateField()),
                ('resultado', models.CharField(choices=[('V', 'Victoria'), ('T', 'Tablas'), ('D', 'Derrota')], default='V', max_length=20)),
                ('video', gll_app.models.ImageKitField(max_length=500, null=True)),
                ('imagen_evento', gll_app.models.ImageKitField(max_length=500, null=True)),
                ('pactada', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pago_juez', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('apuesta_general', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('premio_mayor', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_premio_mayor', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('apuesta_por_fuera', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('condicionGallo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.estado')),
                ('gallo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.gallo')),
                ('galpon1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galpon1', to='gll_app.galpon')),
                ('galpon2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galpon2', to='gll_app.galpon')),
            ],
        ),
    ]
