# Generated by Django 5.2.4 on 2025-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallo',
            name='tipoGallo',
            field=models.CharField(choices=[('DP', 'Gallo De Pelea'), ('PADRE', 'Gallo Padre'), ('MADRE', 'Gallina Madre')], max_length=20),
        ),
    ]
