# Generated by Django 5.2.4 on 2025-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='galpon',
            name='dueno',
        ),
        migrations.AlterField(
            model_name='gallo',
            name='fechaNac',
            field=models.DateField(null=True),
        ),
    ]
