# Generated by Django 5.2.4 on 2025-09-04 00:07

import django.db.models.deletion
import gll_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gll_app', '0002_alter_gallo_tipogallo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', gll_app.models.ImageKitField(max_length=500)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=6)),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Archivo adicional',
                'verbose_name_plural': 'Archivos adicionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
