# Generated by Django 5.2.4 on 2025-07-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0002_remove_gallo_observaciones_remove_galpon_dueno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaCheck',
            fields=[
                ('nroPlaca', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='gallo',
            name='fechaMuerte',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='placaMadre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='gll_app.gallo'),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='placaPadre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='gll_app.gallo'),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='nroPlaca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallo_por_placa', to='gll_app.placacheck'),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='nroPlacaAnterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallo_por_placa_anterior', to='gll_app.placacheck'),
        ),
    ]
