# Generated by Django 5.2.4 on 2025-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0003_placacheck_alter_gallo_fechamuerte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fechaYHora',
            field=models.DateField(),
        ),
    ]
