# Generated by Django 5.2.6 on 2025-09-29 23:16

import gll_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0003_archivosadicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosadicionales',
            name='archivo',
            field=gll_app.models.CloudflareR2Field(max_length=500),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='imagen_evento',
            field=gll_app.models.CloudflareR2Field(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='video',
            field=gll_app.models.CloudflareR2Field(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='nombre_img',
            field=gll_app.models.CloudflareR2Field(max_length=500),
        ),
    ]
