# Generated by Django 5.2.4 on 2025-07-18 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0004_alter_encuentro_fechayhora'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesosCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='gallo',
            name='nroPlaca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallo_por_placa', to='gll_app.placacheck'),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='nroPlacaAnterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallo_por_placa_anterior', to='gll_app.placacheck'),
        ),
        migrations.AlterField(
            model_name='gallo',
            name='peso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.pesoscheck'),
        ),
    ]
