# Generated by Django 5.2.4 on 2025-07-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0005_pesoscheck_alter_gallo_nroplaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallo',
            name='peso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gll_app.pesoscheck'),
        ),
    ]
